services:
  postgres:
    image: postgres:latest             #----> docker pull postgres    (docker run)
    container_name: postgres-sql       #----> --name postgres-sql
    environment:
      POSTGRES_USER: username          #----> -e POSTGRES_USER=username
      POSTGRES_PASSWORD: mypassword    #----> -e POSTGRES_PASSWORD=mypassword
      POSTGRES_DB: demo_db             #----> -e POSTGRES_DB=demo_db
    ports:
      - "5432:5432"                    #----> -p "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   #----> -v postgres_data:/var/lib/postgresql/data


  spring-boot-app:
    image: spring-demo
    depends_on:
      - postgres
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sql:5432/demo_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:


